### ISSUE TITLE
Change color on hover

### ISSUE THREAD

**Issue by laura-chesches** [levrik/mdi-react#16]
Hello, is there any property to use if you want the icon to change the color on mouseover?

**Comment by levrik** [comment]
Hey, you can do that via CSS. Just add an class via the `className` prop and define some CSS, e.g.:

```css
.my-custom-icon:hover {
  fill: #000;
}
```
